name: Deploy to Massdriver
on:
  push:
    branches: [main]

jobs:
  push_and_deploy:
    runs-on: ubuntu-latest
    env:
      MASSDRIVER_ORG_ID: ${{ secrets.MASSDRIVER_ORG_ID }}
      MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions@v4
      - name: Push Image
        uses: massdriver-cloud/actions/image_push@v4
        with:
          namespace: ${{ vars.NAMESPACE }}
          image-name: ${{ vars.IMAGE_NAME }}
          artifact: ${{ secrets.MASSDRIVER_ARTIFACT_ID }}
          region: ${{ vars.REGION }}
          image-tag: ${{ github.sha }}
          build-context: ./ # path to Dockerfile
      - name: Publish Bundle
        uses: massdriver-cloud/actions/bundle_publish@v4
        with:
          build-directory: ./massdriver # path to massdriver config directory, contains massdriver.yaml
      - name: Set Image Version
        uses: massdriver-cloud/actions/app_patch@v4
        with:
          project: decents
          env: prod
          manifest: decentservic
          set: |
            params.image.tag = "${{ github.sha }}"
      - name: Deploy App
        uses: massdriver-cloud/actions/app_deploy@v4
        with:
          project: decents
          env: prod
          manifest: decentservic
